name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test CPU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.11"
          architecture: "x64"
    - name: Installation
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
        python3 -m pip install -e '.[testing]' --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run Pytest
      run: python3 -m pytest -s -v
      