name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test CPU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: "3.10.6"
          architecture: "x64"
    - name: Installation
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        python3 -m pip install -e .
    - name: Run Pytest
      run: python3 -m pytest -s -v