name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test CPU
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: python3 -m pip install -e .
    - name: Run Pytest
      run: python -m pytest -s -v